import pandas as pd
from gpt_extender import DataExtender, ExtendTemplate

# Reading DataFrame
df = pd.read_csv("revievs.csv")

# create extender instance
extender = DataExtender(df)

# add synthetic data generated by gpt
extender.add_synthetic_data(column_name="reviews", output_size=30)


# topic recognition
extender.add_topic(column_name="reviews", 
                   new_column_name="category", 
                   outputs=["product", "service", "other"])


# CUSTOM EXTENSION
# Define data extension template
template = ExtendTemplate(column_name="reviews",
                          new_column_name="sentiment",
                          context="You are a specialist in text review sentiment recognition.",
                          task="Based on provided review evaluate the sentiment.",
                          output="Format response as one word. True if positive, False if negative or neutral."
                          )

# extend data with template, creating custom solution
extender.chat_extend(template=template)

# EMbeddings and similarity search
# add embeddings and perform
extender.add_embeddings(column_name="reviews")

# use cosine similarity to find closes matches
search_results: pd.DataFrame = extender.search_similarity(embedding_column="reviews_embedding", 
                                                          query="There was a problem with sevice.", 
                                                          n_best_results=5)
search_results.head()

# check token usage
extender.usage_summary()

# suggest potentiall data extensions with chat model
extender.ai_analyze(column_name="reviews")